name: ci
on: [push]

jobs:
  activate:
    runs-on: self-ubuntu-22.04
    if: |
      github.repository == 'feelpp/om' &&
      !startsWith(github.event.head_commit.message, 'Release ') &&
      !contains(github.event.head_commit.message, 'ci skip')
    steps:
    - run: echo ready
  
  build:
    runs-on: self-ubuntu-22.04
    needs: activate
    steps:
    - run: |
      
  tests:
    needs: activate
    runs-on: self-ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Installs and upgrades necessary packages
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pandas fmpy 
      - name: tests
        env: 
          TOKEN_API_MERAKI: ${{ secrets.TOKEN_API_MERAKI }}
        run: |
          python3 -m pytest -s

  deliver:
    runs-on: self-ubuntu-22.04
    needs: pytests
    name: Docker Build, Tag, Push

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/feelpp/om-lorenz
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1        
    - 
      name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - 
      name: Build container image
      uses: docker/build-push-action@v2
      with: 
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
